### PR TITLE
Add Tomcat 8 compiler

### PR DESCRIPTION
**Pull request by dcarneir**
Added support for Tomcat 8 compiler, based on Tomcat 7 source.

### CODE REVIEW

**Comment by a-poptsov** [comment]
Good day. Daniel  thank you for your changes. Do anybody know if this changes will be aplied to any maven repo? They are really needed and will be helpfull for java community.

**Comment by leoherbie** [comment]
Any updates on this?

**Comment by HaraldWalker** [comment]
We are also waiting for this. Any news or alternative solutions?

**Comment by timlevett** [comment]
:+1:

**Comment by HaraldWalker** [comment]
Why only Tomcat version 8.0.15? Current version is 8.0.36. 
Pre-compiled classes don't seem to work on newer Tomcat versions (works on 8.0.24, but not on 8.0.28 or higher).

**Comment by HaraldWalker** [comment]
Using Tomcat 8.0.36 for the pre-compilation solves the problem, but those files are then not compatible with an old Tomcat version like 8.0.24 any longer.

**Pull request merged**
