### PR TITLE
Added access to parameters for jspC: Caching, GenStringAsCharArray, PoolingEnabled, ClassDebugInfo.

### PR DESCRIPTION
**Pull request by czerpak**
I added access for this parameters because are very helpful for me and I think this functionality will improve flexibility for jspc-maven-plugin.

### CODE REVIEW

**Comment by vijayaraja** [comment]
can you merge the feature, Please.

**Comment by vijayaraja** [comment]
thanks for merging the changes. when we can expect new version in maven central repository?

**Comment by timlevett** [comment]
Working on it now.

**Comment by vijayaraja** [comment]
thanks lot to czerpak and timlevett.

**Pull request merged**
